
import "./globals.css";
import { inter,ebGaramond } from "../../fonts.js";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${ebGaramond.variable}`}>
      <body

      >
        {children}
      </body>
    </html>
  );
}
